### ISSUE TITLE
关于自动切换内网的方案

### ISSUE THREAD

**Issue by GavinNovate** [asundust/NAS-Nav-iCloud#2]
看到代码中自动切换内网需要部署 Php 服务器，通过判断本机地址来判断是否为内网。

从字面意思来讲，这确实能判断内网，但是内网有很多，到不同环境下的内网可能能判断成功，但是不能访问。

所以我理解判断内网可以尝试主动连接内网的地址，如果连接成功就切换到内网，不成功就还在外网。

这样的好处有两点，

1 .判断内网更准确了，准确的来讲是在所在服务器下的那个内网
2. 不需要Php服务器了，简单的js就可以请求

**Comment by asundust** [comment]
- 目前内网自动切换设计内置了三套逻辑
> 1.根据请求IP是否为局域网IP，该建议根据[#1](https://github.com/asundust/NAS-Nav-iCloud/pull/1)建议改进
> 2.如上述为否，据客户端IP和服务端的IP是否相等
> 3.如上述为否，根据是否能访问服务端的内网IP进行判断

- 方案3有个棘手问题，涉及到跨域请求，目前不知道纯JS方案如何去操作，不吝赐教
- 自动内外网设计的初衷也是不想另起服务的，毕竟也是负担，但是最终设计下来还是发现起服务最方便。

纠错，在新版中调整了逻辑，1和2顺序错了，上述展示现已改为正确顺序。

**Comment by asundust** [comment]
补充：“到不同环境下的内网可能能判断成功，但是不能访问”
针对这个，我是有判断返回值的，除非这个返回值和我定义的返回值是一致（JSONP返回，且定义的变量名为`lan`，非常见的`code`、`result`、`status`等），那真的太巧合了，如果这个是影响到的话，可以加点特殊返回值的标记，确保是该服务返回的。

**Comment by GavinNovate** [comment]
其实我 fork 了这个仓库自己又修改了一下，可以查看这里 https://github.com/GavinNovate/NAS-Nav-iCloud

说一下我的场景，我有外网 IP，但是不能用 80 和 443 端口，所以我在外网就用了 4433 端口，内网依然用 443 端口；我的域名都是一样的，可能不存在跨域问题；所以我的处理很简单，就是在页面启动时，通过 head 请求一下，看看 443 端口能不能通，能通就切到内网，不能通就保持外网。

在我的场景下，这个解决方案是完全可行的，看到你的回复，可能我们的场景不同。

**Comment by asundust** [comment]
目前你的方案稍显局限，只能针对特定场景和环境去使用，代码mark，未来可以用上将更新上。
``` js
// 尝试访问内网地址
const url = 'https://abc.com';
const xhr = new XMLHttpRequest();
xhr.open('HEAD', url, true);
xhr.onload = function() {
    // 如果访问成功则切换到内网
    const qiehCheckbox = document.getElementById('qieh');
    qiehCheckbox.checked = xhr.status === 200;
    if ($("#qieh").is(":checked")) {
        $("#app").css("display", "none");
        $("#app1").css("display", "block")
    } else {
        $("#app1").css("display", "none");
        $("#app").css("display", "block")
    }
};
xhr.send();
```

**Comment by GavinNovate** [comment]
是的，可以作为参考

**Comment by GavinNovate** [comment]
> 目前你的方案稍显局限，只能针对特定场景和环境去使用，代码mark，未来可以用上将更新上。
> 
> ```js
> // 尝试访问内网地址
> const url = 'https://xxx.com';
> const xhr = new XMLHttpRequest();
> xhr.open('HEAD', url, true);
> xhr.onload = function() {
>     // 如果访问成功则切换到内网
>     const qiehCheckbox = document.getElementById('qieh');
>     qiehCheckbox.checked = xhr.status === 200;
>     if ($("#qieh").is(":checked")) {
>         $("#app").css("display", "none");
>         $("#app1").css("display", "block")
>     } else {
>         $("#app1").css("display", "none");
>         $("#app").css("display", "block")
>     }
> };
> xhr.send();
> ```

可不可以修改一下你的这个回复，把我的域名打个码？

**Comment by asundust** [comment]
已处理
